[package]
name = "chain"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
hex = "0.4.3"
dyn-clone = "1.0.17"
sys            = {path = "../sys"}
field          = {path = "../field"}
basis          = {path = "../basis"}
protocol       = {path = "../protocol"}

